# Generated by Django 3.0.13 on 2021-03-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='pinterest_url',
            field=models.URLField(blank=True),
        ),
    ]
