# Generated by Django 3.0.13 on 2021-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0002_auto_20210316_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='template_theme',
            field=models.CharField(choices=[('Dark_Theme', 'Dark Theme'), ('Light_Theme', 'Light Theme')], default='Dark_Theme', max_length=250),
        ),
    ]
