# Generated by Django 3.0.13 on 2021-03-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0003_auto_20210319_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrypage',
            name='template_theme',
        ),
    ]
