# Generated by Django 3.0.13 on 2021-03-20 01:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ActorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('actor_name', models.CharField(max_length=200)),
                ('actor_bio', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CharacterIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CharacterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('character_name', models.CharField(max_length=250)),
                ('character_description', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MovieIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProducerIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProducerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('producer_name', models.CharField(max_length=200)),
                ('producer_bio', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MoviePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('movie_title', models.CharField(max_length=250)),
                ('film_number', models.IntegerField()),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='\n        Enter in a rating for this movie. Note: Can enter up to a tens place, e.g, 4.5.', max_digits=4, null=True)),
                ('movie_description', wagtail.core.fields.RichTextField(help_text='Describe the movie.')),
                ('jove_brand_actor', models.ForeignKey(blank=True, help_text="Choose the actor that plays Jove Brand. If you don't see your actor listed here, \n        it's probably because you didn't make the Actor Page yet!", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watchlist.ActorPage')),
                ('producer', models.ForeignKey(blank=True, help_text="Choose a producer. If you don't see your producer listed here, \n        it's probably because you didn't make the Producer Page yet!", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watchlist.ProducerPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DossierPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField()),
                ('actor_page', models.ForeignKey(blank=True, help_text='Choose the character index page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watchlist.ActorIndexPage')),
                ('character_page', models.ForeignKey(blank=True, help_text='Choose the character index page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watchlist.CharacterIndexPage')),
                ('producer_page', models.ForeignKey(blank=True, help_text='Choose the character index page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watchlist.ProducerIndexPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
