# Generated by Django 3.0.13 on 2021-03-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerpage',
            name='producer_name',
        ),
    ]
