# Generated by Django 3.0.13 on 2021-03-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_remove_producerpage_producer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepage',
            name='release_date',
        ),
    ]
