# Generated by Django 3.0.13 on 2021-03-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_remove_moviepage_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorpage',
            name='actor_name',
        ),
    ]
