# Generated by Django 3.0.13 on 2021-03-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_remove_actorpage_actor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterpage',
            old_name='character_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='characterpage',
            name='character_name',
        ),
    ]
