# Generated by Django 3.0.13 on 2021-03-16 19:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210316_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='caption_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
