# Generated by Django 3.0.13 on 2021-03-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0004_auto_20210316_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanSiteHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('a_page', models.ForeignKey(blank=True, help_text="Choose a page to assign to 'A' value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('d_page', models.ForeignKey(blank=True, help_text="Choose a page to assign to 'D' value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('e_page', models.ForeignKey(blank=True, help_text="Choose a page to assign to 'E' value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('n_page', models.ForeignKey(blank=True, help_text="Choose a page to assign to 'N' value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('r_page', models.ForeignKey(blank=True, help_text="Choose a page to assign to 'R' value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('w_page', models.ForeignKey(blank=True, help_text="Choose a page to assign to 'W' value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
