# Generated by Django 3.1.7 on 2021-03-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('home', '0007_remove_fansitehomepage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='book_link_page',
            field=models.ForeignKey(blank=True, help_text="Optional field: if you'd like your main book image to link to a book page, \n        choose that page here.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.bookpage'),
        ),
    ]
