# Generated by Django 3.1.7 on 2021-03-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_book_link_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='background_image',
            new_name='author_image',
        ),
    ]
