# Generated by Django 3.1.7 on 2021-03-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210331_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='caption_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
