# Generated by Django 3.1.7 on 2021-04-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0011_homepage_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_question', models.CharField(help_text='Type in whatever you would like your spam question to be.', max_length=250)),
                ('spam_answer', models.CharField(help_text='Type the answer to your spam question.', max_length=250)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
