# Generated by Django 3.1.7 on 2021-04-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_spamsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpamSettings',
        ),
    ]
