# Generated by Django 3.1.7 on 2021-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_spamsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Your TikTok URL', null=True),
        ),
    ]
