# Generated by Django 3.0.13 on 2021-03-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='template_theme',
            field=models.CharField(choices=[('base_dark.html', 'Dark'), ('base_light.html', 'Light')], default='Dark', help_text='\n        Choose dark theme to match main site and light theme\n        to match light site.', max_length=250),
        ),
    ]
